apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webapp-prod

resources:
  - ../../base

commonLabels:
  environment: prod

patches:
  - path: patch-replicas.yaml
  - path: patch-hpa.yaml

images:
  - name: ACLOGIN_SERVER_PLACEHOLDER/webapp
    newName: acraidlcprod.azurecr.io/webapp
    newTag: prod-latest # updated by the CD workflow on each release
